site_name: Template Python Project
site_url: https://phillipefs.github.io/template-python-project/
theme:
  name: material
  palette:
    primary: blue
  language: en

repo_name: "template-python-project"
repo_url: "https://github.com/phillipefs/template-python-project"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
